### ISSUE TITLE
What to name this not-distro package?

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/honeycomb-opentelemetry-ruby#8]
Will we have a conventional name for the not-distro packages across all the languages?

This project is currently wired up to publish as `honeycomb-opentelemetry`.

`honeycomb-opentelemetry` is the established—for good or for meh—name for the Honeycomb OTel Distro in various languages. However, the standalone components will be published in a separate library under a different name, at least for Python where the distro package cannot be depended upon without triggering Distro behavior.

**Comment by codeboten** [comment]
My proposed name is `honeycomb-opentelemetry-components`, unless we want to release each component individually.

**Comment by MikeGoldsmith** [comment]
Yep, I like `honeycomb-opentelemetry-components` as the components package.

I'm on the fence for naming conventions as we'll have inconsistency with either option. We have `honeycomb-opentelemetry` for all the other languages which is both the distro plus components. We _need_ to create a separate package for python because of the auto-instrumentation hook, we probably don't for the others (.NET, go, JS, etc).

Options:
1) Go for consistency of always having `honeycomb-opentelemetry` which can be distro + components, creating the components sub-package if needed later
  _ ruby will be an exception because it will not include a distro
2) Go for `honeycomb-opentelemetry-components` which only ruby & python will have
  _ ruby will be an exception because it won't have a `honeycomb-opentelemetry` package

I like 1) for package naming consistency. The components sub-package is only created when needed.

**Comment by MikeGoldsmith** [comment]
We're not going ahead with the ruby distro for now.
